### ISSUE TITLE
Exemplar support

### ISSUE THREAD

**Issue by emschwartz** [autometrics-dev/autometrics-shared#18]
Prometheus and OpenTelemetry support attaching [exemplars](https://grafana.com/docs/grafana/latest/fundamentals/exemplars/) to metrics. It would be useful to provide support for this out of the box with autometrics.

Ideally, we would integrate with whatever popular libraries are used for to add tracing in each language so that we could automatically attach the `trace_id` to the metrics.

The biggest problem I foresee with this is that exemplars are not well-supported across many of the OpenTelemetry and Prometheus client libraries. We will either need to submit PRs to add support for exemplars upstream, wait until they are added, or support this feature only when autometrics is being used in combination with a metrics library that supports exemplars.

- [x] Spec https://github.com/autometrics-dev/autometrics-shared/pull/25
- [x] Rust https://github.com/autometrics-dev/autometrics-rs/issues/26 (only using the `prometheus-client` backend)
- [x] Python https://github.com/autometrics-dev/autometrics-py/issues/41 (only using the `prometheus-client` package)
- [ ] TS https://github.com/autometrics-dev/autometrics-ts/issues/57
- [x] Go https://github.com/autometrics-dev/autometrics-go/issues/44 (only using the prometheus client)
- [ ] C#
- [ ] Java

**Comment by emschwartz** [comment]
Since exemplar support is optional and in a number of cases blocked on upstream support for it in the Prometheus/OpenTelemetry client libraries, I am going to close this issue for now.
