### ISSUE TITLE
Concurrency tracking option

### ISSUE THREAD

**Issue by emschwartz** [autometrics-dev/autometrics-shared#26]
- [x] [Spec](https://github.com/autometrics-dev/autometrics-shared/blob/main/SPEC.md#functioncallsconcurrent)
- [x] Rust
- [x] Go
- [x] Typescript
- [x] Python https://github.com/autometrics-dev/autometrics-py/issues/42
- [ ] C# https://github.com/autometrics-dev/autometrics-cs/issues/10
- [ ] Dashboards https://github.com/autometrics-dev/autometrics-shared/issues/5
- [ ] Java https://github.com/jamsiedaly/autometricsj/issues/2
